import { defineStore } from 'pinia'

export const useSupportTicketListStore = defineStore('SupportTicketListStore', {
  actions: {
    // 👉 Fetch all AuditTrails
    fetchTicket(params) {
      console.log("fetchTicket")
      console.log("params",params)


      // return axios.get('apps/auditTrails', { params })
      const res = {
        data: {
          tickets : [
            {
              ticket_id: '13',
              customer_phone_number: '6281210028232',
              name: 'Lisa',
              status: 'Close',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Wifi rusak",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '14',
              customer_phone_number: '6281210028232',
              name: 'Satria',
              status: 'Open',
              initiated_type: 'Bis',
              category: 'Marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Mesin cuci rusak",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '15',
              customer_phone_number: '6281210028232',
              name: 'Fitya',
              status: 'Service',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Sepeda rusak",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '16',
              customer_phone_number: '6281210028232',
              name: 'Gina',
              status: 'Close',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Laptop rusak",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '17',
              customer_phone_number: '6281210028232',
              name: 'Vicky',
              status: 'Service',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Sinyal hilang",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '17',
              customer_phone_number: '6281210028232',
              name: 'Vicky',
              status: 'Close',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Sinyal hilang",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '17',
              customer_phone_number: '6281210028232',
              name: 'Vicky',
              status: 'Service',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Sinyal hilang",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '17',
              customer_phone_number: '6281210028232',
              name: 'Vicky',
              status: 'Service',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Sinyal hilang",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
            {
              ticket_id: '17',
              customer_phone_number: '6281210028232',
              name: 'Vicky',
              status: 'Service',
              initiated_type: 'cis',
              category: 'marketing',
              priority: 'Low',
              user_name: 'diniagent',
              channel: "READ",
              description: "Sinyal hilang",
              note: "apa kabar?",
              updated_tstamp: 1692001077,
              created_tstamp: 1691997372,
            },
          ],
          total_pages : 1,
          total_rows : 5,
        },
      }

      console.log("res:",res)
      
      return Promise.resolve(res)
    },
  },
})
